import {test,expect,type Page} from '@playwright/test';
import {readFileSync,existsSync} from 'node:fs';
const hasFixture=existsSync('private/access-integration/config.json');const fixture=hasFixture?JSON.parse(readFileSync('private/access-integration/config.json','utf8')):{};test.skip(!hasFixture||process.env.WCI_LIVE_TESTS!=='1','Isolated live fixture required');test.use({actionTimeout:10000});
async function login(page:Page,role:string){await page.goto('/');await page.getByLabel('Email',{exact:true}).fill(fixture.email[role]);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page.locator('.app-shell')).toBeVisible({timeout:20000});}
test('live sessions apply scoped roles, Regional Done, realtime updates, mode isolation and user provisioning',async({browser})=>{
 test.setTimeout(120000);const superContext=await browser.newContext(),personContext=await browser.newContext(),headContext=await browser.newContext();const admin=await superContext.newPage(),person=await personContext.newPage(),head=await headContext.newPage();const errors:string[]=[];for(const p of [admin,person,head])p.on('pageerror',e=>errors.push(e.message));
 await login(admin,'super');await login(person,'person');await login(head,'head');
 await expect(person.locator('.sidebar nav button')).toHaveCount(1);await expect(person.locator('.records tbody tr')).toHaveCount(1);await expect(person.locator('.records')).toContainText('Test Company 1');await expect(person.locator('.records')).not.toContainText('Test Company 2');await expect(head.locator('.records tbody tr')).toHaveCount(3);
 await person.locator('.records tbody .text-button').first().click();await person.getByRole('button',{name:'Tandai Selesai',exact:true}).click();await expect(person.getByRole('dialog')).toHaveCount(0);await expect(head.locator('.records tbody tr').filter({hasText:'Test Company 1'})).toContainText('Done',{timeout:15000});
 await admin.getByRole('button',{name:'Admin',exact:true}).click();await expect(admin.getByRole('button',{name:'Pengguna & Akses',exact:true})).toBeVisible();await admin.getByRole('button',{name:'Upload & Riwayat Data',exact:true}).click();await admin.getByLabel('Dashboard tujuan',{exact:true}).selectOption('regional');await admin.locator('input[type=file]').setInputFiles({name:'weekly-regional.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await makeUpload()});await expect(admin.getByRole('button',{name:'Terapkan Upload',exact:true})).toBeEnabled();await admin.getByRole('button',{name:'Terapkan Upload',exact:true}).click();await expect(admin.getByRole('status')).toContainText('Upload tersimpan');await expect(head.locator('.records tbody tr')).toHaveCount(4,{timeout:15000});await expect(head.locator('.records tbody tr').filter({hasText:'Test Company 1'})).toContainText('Done');
 await admin.getByRole('button',{name:'Pengguna & Akses',exact:true}).click();await admin.getByRole('button',{name:'Buat Pengguna',exact:true}).click();await admin.getByLabel('Nama lengkap',{exact:true}).fill('Provisioned Test User');await admin.locator('.admin-inline-editor').getByLabel('Email',{exact:true}).fill('created-'+fixture.ids.workspace+'@wci-test.invalid');await admin.getByLabel('Password sementara',{exact:true}).fill(fixture.password);await admin.locator('.admin-inline-editor').getByLabel('Role',{exact:true}).selectOption('individual');await admin.locator('.admin-grants').getByLabel('Regional - Non BNIDirect',{exact:true}).check();await admin.getByLabel('Nama PIC sesuai sumber data',{exact:true}).fill('Person A');await admin.locator('.admin-inline-editor').getByRole('button',{name:'Simpan',exact:true}).click();await expect(admin.getByRole('status')).toContainText('Pengguna dan akses berhasil disimpan.',{timeout:20000});await expect(admin.getByLabel('Link aktivasi',{exact:true})).toHaveCount(0);
 // Role updates are read from the database, without requiring the viewer to sign in again.
 const row=admin.locator('tbody tr').filter({has:admin.getByText('Test person',{exact:true})});await row.getByRole('button',{name:'Edit',exact:true}).click();await admin.locator('.admin-inline-editor').getByLabel('Status',{exact:true}).selectOption('false');await admin.locator('.admin-inline-editor').getByRole('button',{name:'Simpan',exact:true}).click();await expect(person.getByText('Akun tidak aktif. Hubungi administrator.',{exact:true})).toBeVisible({timeout:15000});
 expect(errors).toEqual([]);await admin.screenshot({path:'private/access-integration/admin-users.png',fullPage:true});await superContext.close();await personContext.close();await headContext.close();
});
async function makeUpload(){const XLSX=await import('xlsx'),rows=JSON.parse(readFileSync('private/access-integration/regional.json','utf8'));rows.push({...rows[1],company:'Test Company 4',cid:'4'});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Regional');return XLSX.write(wb,{type:'buffer',bookType:'xlsx'}) as Buffer;}

test('created account must change its temporary password before accessing mapped jobs',async({page})=>{
 await login(page,'super');await page.evaluate(async f=>{const modulePath='/src/lib/supabase.ts';const {supabase:db}=await import(/* @vite-ignore */ modulePath);const target=await db.from('wci_profiles').select('user_id').eq('workspace_id',f.ids.workspace).eq('name','Provisioned Test User').single();const r=await db.functions.invoke('wci-user-admin',{body:{workspace:f.ids.workspace,action:'reset',user_id:target.data.user_id,password:f.password}});if(r.error||r.data.error)throw new Error(r.error?.message||r.data.error);await db.auth.signOut();},fixture);await page.goto('/');await page.getByLabel('Email',{exact:true}).fill('created-'+fixture.ids.workspace+'@wci-test.invalid');await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Login',exact:true}).click();
 await expect(page.locator('.password-setup')).toBeVisible({timeout:20000});await expect(page.locator('.app-shell')).toHaveCount(0);
 const before=await page.evaluate(async f=>{const modulePath='/src/lib/supabase.ts';const {supabase:db}=await import(/* @vite-ignore */ modulePath);return await db.from('wci_records').select('id').eq('workspace_id',f.ids.workspace);},fixture);expect(before.data??[]).toEqual([]);if(before.error)expect(before.error.code).toBe("42501");
 const password=fixture.password+'New1!';await page.getByLabel('Password baru',{exact:true}).fill(password);await page.getByLabel('Konfirmasi password',{exact:true}).fill(password);await page.getByRole('button',{name:'Simpan Password',exact:true}).click();
 await expect(page.locator('.app-shell')).toBeVisible({timeout:20000});await expect(page.locator('.sidebar nav button')).toHaveCount(1);await expect(page.locator('.records')).toContainText('Test Company 1');await expect(page.locator('.records')).not.toContainText('Test Company 2');
});


