import {test,expect,type Page} from '@playwright/test';
import {readFileSync,existsSync} from 'node:fs';
const hasFixture=existsSync('private/access-integration/config.json');const fixture=hasFixture?JSON.parse(readFileSync('private/access-integration/config.json','utf8')):{};test.skip(!hasFixture||process.env.WCI_LIVE_TESTS!=='1','Isolated live fixture required');test.use({actionTimeout:10000});
async function login(page:Page,role:string){await page.goto('/');await page.getByLabel('Email',{exact:true}).fill(fixture.email[role]);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page.locator('.app-shell')).toBeVisible({timeout:20000});}
test('live sessions apply scoped roles, Regional Done, realtime updates, mode isolation and user provisioning',async({browser})=>{
 test.setTimeout(120000);const superContext=await browser.newContext(),personContext=await browser.newContext(),headContext=await browser.newContext();const admin=await superContext.newPage(),person=await personContext.newPage(),head=await headContext.newPage();const errors:string[]=[];for(const p of [admin,person,head])p.on('pageerror',e=>errors.push(e.message));
 await login(admin,'super');await login(person,'person');await login(head,'head');
 await expect(person.locator('.sidebar nav button')).toHaveCount(1);await expect(person.locator('.records tbody tr')).toHaveCount(1);await expect(person.locator('.records')).toContainText('Test Company 1');await expect(person.locator('.records')).not.toContainText('Test Company 2');await expect(head.locator('.records tbody tr')).toHaveCount(3);
 await person.locator('.records tbody .text-button').first().click();await person.getByRole('button',{name:'Tandai Selesai',exact:true}).click();await expect(person.getByRole('dialog')).toHaveCount(0);await expect(head.locator('.records tbody tr').filter({hasText:'Test Company 1'})).toContainText('Done',{timeout:15000});
 await admin.getByRole('button',{name:'Admin',exact:true}).click();await expect(admin.getByRole('button',{name:'Pengguna & Akses',exact:true})).toBeVisible();await admin.getByRole('button',{name:'Upload & Riwayat Data',exact:true}).click();await admin.getByLabel('Dashboard tujuan',{exact:true}).selectOption('regional');await admin.locator('input[type=file]').setInputFiles({name:'weekly-regional.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await makeUpload()});await expect(admin.getByRole('button',{name:'Terapkan Upload',exact:true})).toBeEnabled();await admin.getByRole('button',{name:'Terapkan Upload',exact:true}).click();await expect(admin.getByRole('status')).toContainText('Upload tersimpan');await expect(head.locator('.records tbody tr')).toHaveCount(4,{timeout:15000});await expect(head.locator('.records tbody tr').filter({hasText:'Test Company 1'})).toContainText('Done');
 await admin.getByRole('button',{name:'Pengguna & Akses',exact:true}).click();await admin.getByRole('button',{name:'Buat Pengguna',exact:true}).click();await admin.getByLabel('Nama lengkap',{exact:true}).fill('Provisioned Test User');await admin.locator('.admin-inline-editor').getByLabel('Email',{exact:true}).fill('created-'+fixture.ids.workspace+'@wci-test.invalid');await admin.locator('.admin-inline-editor').getByLabel('Role',{exact:true}).selectOption('individual');await admin.locator('.admin-grants').getByLabel('Regional - Non BNIDirect',{exact:true}).check();await admin.getByLabel('Nama PIC sesuai sumber data',{exact:true}).fill('Person A');await admin.locator('.admin-inline-editor').getByRole('button',{name:'Simpan',exact:true}).click();await expect(admin.getByRole('status')).toContainText('Pengguna dan akses berhasil disimpan.',{timeout:20000});await expect(admin.getByLabel('Link aktivasi',{exact:true})).toHaveValue(/https:/,{timeout:20000});
 // Role updates are read from the database, without requiring the viewer to sign in again.
 const row=admin.locator('tbody tr').filter({has:admin.getByText('Test person',{exact:true})});await row.getByRole('button',{name:'Edit',exact:true}).click();await admin.locator('.admin-inline-editor').getByLabel('Status',{exact:true}).selectOption('false');await admin.locator('.admin-inline-editor').getByRole('button',{name:'Simpan',exact:true}).click();await expect(person.getByText('Akun tidak aktif. Hubungi administrator.',{exact:true})).toBeVisible({timeout:15000});
 expect(errors).toEqual([]);await admin.screenshot({path:'private/access-integration/admin-users.png',fullPage:true});await superContext.close();await personContext.close();await headContext.close();
});
async function makeUpload(){const XLSX=await import('xlsx'),rows=JSON.parse(readFileSync('private/access-integration/regional.json','utf8'));rows.push({...rows[1],company:'Test Company 4',cid:'4'});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Regional');return XLSX.write(wb,{type:'buffer',bookType:'xlsx'}) as Buffer;}

test('created account activation and sign-in use only its mapped data',async({page})=>{
 await login(page,'super');
 const result=await page.evaluate(async(f)=>{
  const {supabase:db}=await import('/src/lib/supabase.ts');
  const target=await db.from('wci_profiles').select('user_id').eq('workspace_id',f.ids.workspace).eq('name','Provisioned Test User').single();if(target.error)throw new Error(target.error.message);
  const setup=await db.functions.invoke('wci-user-admin',{body:{workspace:f.ids.workspace,action:'reset',user_id:target.data.user_id}});if(setup.error||setup.data.error)throw new Error(setup.error?.message||setup.data.error);
  const token=new URL(setup.data.link).searchParams.get('token');await db.auth.signOut();const verify=await db.auth.verifyOtp({token_hash:token,type:'recovery'});if(verify.error)throw new Error(verify.error.message);const update=await db.auth.updateUser({password:f.password});if(update.error)throw new Error(update.error.message);await db.auth.signOut();const sign=await db.auth.signInWithPassword({email:'created-'+f.ids.workspace+'@wci-test.invalid',password:f.password});if(sign.error)throw new Error(sign.error.message);
  const rows=await db.from('wci_records').select('payload').eq('workspace_id',f.ids.workspace);if(rows.error)throw new Error(rows.error.message);return rows.data.every(r=>r.payload.implementor==='Person A')&&rows.data.length>0;
 },fixture);expect(result).toBe(true);
});
