import { describe,it,expect } from 'vitest';
import { mergeUpload } from '../src/domain/data-identity';
import { scopedRows,type Profile,type Grant,type Team } from '../src/lib/access';
import { pilotReportModel } from '../src/piloting/reports';
import { pilotSla } from '../src/piloting/sla';
import { type Payload } from '../src/types';
describe('versioned uploads',()=>{
 const row:Payload={company:'A',cid:'100',product:'VA',type:'Maintenance',salesDate:'2026-08-03',status:'Pending',implementor:'Desta'};
 it('updates mutable status/PIC, skips identical rows, merges partial uploads and detects conflicts',()=>{const b={...row,cid:'200',company:'B'};const r=mergeUpload('regional',[row,b],[{...row,status:'Done',implementor:'Resti'},{...row,status:'Done',implementor:'Resti'}]);expect(r.rows).toHaveLength(2);expect(r).toMatchObject({newRows:0,updated:1,duplicates:1,unchanged:0});expect(mergeUpload('regional',r.rows,r.rows)).toMatchObject({unchanged:2,updated:0});expect(()=>mergeUpload('regional',[],[row,{...row,status:'Done'}])).toThrow(/berbeda/);});
 it('preserves Done changes when an older spreadsheet is uploaded',()=>{const done={...row,status:'Done',dashboardUpdatedAt:'2026-10-04T00:00:00Z',dashboardNote:'Selesai'};expect(mergeUpload('regional',[done],[row]).rows[0]).toEqual(done);});
 it('does not merge different requests from the same company or missing identity fields',()=>{expect(mergeUpload('regional',[row],[{...row,salesDate:'2026-08-04'}]).rows).toHaveLength(2);expect(()=>mergeUpload('regional',[],[{...row,salesDate:null}])).toThrow(/Identitas/);expect(mergeUpload('piloting',[],[{'No. Register':'A','PIC AT':'Desta'}]).rows).toHaveLength(1);});
});
describe('dashboard access',()=>{
 const p:Profile={workspace_id:'w',user_id:'u',name:'User',email:'x@example.test',role:'individual',active:true};
 const grants:Grant[]=[{dataset:'regional',source:'AT',pic:'Desta',team_id:'t'}],teams:Team[]=[{id:'t',workspace_id:'w',dataset:'regional',source:'AT',name:'Team',leader_id:'u'}],people=[{team_id:'t',pic:'Desta'}];const rows=[{payload:{implementor:'Desta'}},{payload:{implementor:'Resti'}}];
 it('restricts individuals/team leaders, leaves unmapped users empty and excludes other dashboards/PM',()=>{expect(scopedRows(rows,'regional',p,grants,teams,people)).toHaveLength(1);expect(scopedRows(rows,'corporate',p,grants,teams,people)).toHaveLength(0);expect(scopedRows(rows,'regional',{...p,role:'team_leader'},grants,teams,people)).toHaveLength(1);expect(scopedRows(rows,'regional',{...p,role:'team_leader'},grants,[],people)).toHaveLength(0);expect(scopedRows(rows,'regional',p,[{...grants[0],pic:''}],teams,people)).toHaveLength(0);expect(scopedRows(rows,'regional',p,[{...grants[0],source:'PM'}],teams,people)).toHaveLength(0);});
 it('grants full scoped viewing to department heads and super admins, but no analytics to admin/inactive accounts',()=>{expect(scopedRows(rows,'regional',{...p,role:'department_head'},grants,teams,people)).toHaveLength(2);expect(scopedRows(rows,'corporate',{...p,role:'department_head'},grants,teams,people)).toHaveLength(0);expect(scopedRows(rows,'corporate',{...p,role:'super_admin'},[],[],[])).toHaveLength(2);expect(scopedRows(rows,'regional',{...p,role:'admin'},grants,teams,people)).toHaveLength(0);expect(scopedRows(rows,'regional',{...p,active:false},grants,teams,people)).toHaveLength(0);});
});
it('packs All AT discrepancy cases into a table without dropping any original detail, for both All and individual reports',()=>{const payload:Payload={'No. Register':'A','Nama Perusahaan':'A Ltd','PIC AT':'Desta','Kategori':'Done','Status Discrepancy':'Discrepancy','Alasan Discrepancy':'Reason '.repeat(80),'Komitmen Discrepancy':'Commitment','Pemenuhan Discrepancy':'Pending'};const rows=[payload,{...payload,'No. Register':'B'}].map((payload,i)=>({id:String(i),payload,sla:pilotSla(payload)}));const m=pilotReportModel(rows,'',['discrepancy','highlights']);expect(m.pages[0].headers).toHaveLength(7);expect(m.pages[0].rows).toHaveLength(2);expect(m.pages[0].rows[0][4]).toBe(String(payload['Alasan Discrepancy']).trim());expect(m.pages[1].rows).toHaveLength(6);const individual=pilotReportModel(rows,'Desta',['discrepancy']);expect(individual.pages).toHaveLength(1);expect(individual.pages[0].rows).toEqual(m.pages[0].rows);expect(individual.pages[0].headers).toHaveLength(7);});
