import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test.beforeEach(async ({ page }) => { await page.goto('/'); await page.getByRole('button', { name: 'Buka preview lokal' }).click(); await expect(page.locator('.kpi').first()).toContainText('1,000'); });
test('navigation, filtering, pagination, record details and all three dashboards', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.getByLabel('Status', { exact: true }).selectOption('Proses Selesai');
    await expect(page.locator('.chips')).toContainText('Proses Selesai');
    await expect(page.locator('tbody tr')).toHaveCount(25);
    await page.getByRole('button', { name: 'Reset', exact: true }).click();
    await page.getByRole('button', { name: 'Halaman berikutnya' }).click();
    await expect(page.locator('.pagination')).toContainText('26–50');
    await page.getByRole('button', { name: 'Detail', exact: true }).first().click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.locator('.detail-grid')).toContainText('Application Number');
    await page.getByRole('button', { name: 'Tutup detail' }).click();
    await page.getByRole('button', { name: 'Proses & Durasi', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Total Process' })).toBeVisible();
    await page.getByRole('button', { name: 'PIC & Beban Kerja', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'KPI Per Person', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Kinerja SLA', exact: true }).click();
    await expect(page.locator('.kpis')).toContainText('SLA Achievement');
    await page.getByRole('button', { name: 'Regional - Non BNIDirect', exact: true }).click();
    await expect(page.locator('.kpi').first()).toContainText('1,098');
    await page.getByRole('button', { name: 'Status Implementasi', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Milestone Availability' })).toBeVisible();
    await page.getByRole('button', { name: 'Corporate - Non Piloting', exact: true }).click();
    await expect(page.locator('.kpi').first()).toContainText('4,509');
    await page.getByRole('button', { name: 'Kinerja SLA', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Official SLA Target Reference' })).toBeVisible();
    expect(errors).toEqual([]);
});
test('spreadsheet validation, apply and restore original dataset', async ({ page }) => {
    await page.getByRole('button', { name: 'Data', exact: true }).click();
    await page.locator('input[type=file]').setInputFiles({ name: 'verification.csv', mimeType: 'text/csv', buffer: Buffer.from('Application Number,Status,Request Date,Applicant Name\nTEST-1,Proses Selesai,2026-10-01,Test Company\nTEST-2,Dalam Proses,2026-10-01,Test Company\n,Done,2026-10-01,Missing ID\n') });
    await expect(page.getByRole('button', { name: 'Success (2)' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Perlu Revisi (1)' })).toBeVisible();
    await page.getByRole('button', { name: 'Terapkan 2 record' }).click();
    await expect(page.locator('.records')).toContainText('2 records');
    await page.getByRole('button', { name: 'Pulihkan dataset asli' }).click();
    await page.getByRole('button', { name: 'Pulihkan sekarang' }).click();
    await expect(page.locator('.records')).toContainText('1,000 records');
});
test('CSV, Word and PowerPoint downloads are generated without runtime errors', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    const sourceId = (await page.locator('tbody tr').first().locator('td').first().innerText()).trim();
    await page.getByLabel('Cari data').fill(sourceId);
    await expect(page.locator('tbody tr')).toHaveCount(1);
    const csvPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'CSV', exact: true }).click();
    const csv = await csvPromise;
    expect((await readFile((await csv.path())!)).toString()).toContain(sourceId);
    await page.getByRole('button', { name: 'Report', exact: true }).click();
    await page.getByLabel('Format', { exact: true }).selectOption('docx');
    let dl = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Generate Report' }).click();
    const docx = await dl;
    await docx.saveAs('private/verified-report.docx');
    expect((await readFile('private/verified-report.docx')).subarray(0, 2).toString()).toBe('PK');
    await page.getByLabel('Format', { exact: true }).selectOption('pptx');
    dl = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Generate Report' }).click();
    const pptx = await dl;
    await pptx.saveAs('private/verified-report.pptx');
    expect((await readFile('private/verified-report.pptx')).subarray(0, 2).toString()).toBe('PK');
    expect(errors).toEqual([]);
});
test('mobile dashboard fits the viewport and remains usable', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'private/mobile-dashboard.png', fullPage: true });
    const dimensions = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }));
    expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width + 2);
    await page.getByRole('button', { name: 'Corporate - Non Piloting', exact: true }).click();
    await expect(page.locator('.kpi').first()).toContainText('4,509');
});

test('request period uses custom calendar range and can return to all periods', async ({ page }) => {
    await page.getByRole('button', { name: 'All Period', exact: true }).click();
    const calendar = page.getByRole('dialog', { name: 'Request Period', exact: true });
    await calendar.getByLabel('Custom Date', { exact: true }).check();
    await calendar.getByLabel('Start Date', { exact: true }).fill('2025-07-01');
    await calendar.getByLabel('End Date', { exact: true }).fill('2025-07-31');
    await calendar.getByRole('button', { name: 'Apply', exact: true }).click();
    await expect(page.locator('.chips')).toContainText('2025-07-01');
    await expect(page.locator('.chips')).toContainText('2025-07-31');
    await page.locator('.period-trigger').click();
    await calendar.getByLabel('All Period', { exact: true }).check();
    await calendar.getByRole('button', { name: 'Apply', exact: true }).click();
    await expect(page.locator('.kpi').first()).toContainText('1,000');
});
