import { test,expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
test.beforeEach(async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Buka preview lokal'}).click();await page.getByRole('button',{name:'Corporate - Piloting',exact:true}).click();await expect(page.locator('.pilot-cards .kpi strong')).toHaveText(['257','238','15','4','7']);});
test('five menus, group filters, duration counts and per-person drilldown preserve source',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('.tabs button')).toHaveText(['Ringkasan','Proses Implementasi','Kinerja & Beban Kerja','Report','Data']);
 await page.getByLabel('Kelompok',{exact:true}).selectOption('COB1');await expect(page.locator('.pilot-cards .kpi strong').first()).toHaveText('70');await page.getByRole('button',{name:'Reset Filter',exact:true}).click();
 await page.getByRole('button',{name:'Proses Implementasi',exact:true}).click();await expect(page.locator('.duration-grid strong')).toHaveText(['151','41','19','27','0']);await expect(page.locator('.records .table-heading small')).toHaveText('7 data');await page.locator('.records tbody .text-button').first().click();await expect(page.getByRole('dialog')).toContainText('Alasan Discrepancy');await expect(page.getByRole('dialog')).toContainText('TIDAK ADA');await page.getByLabel('Tutup detail').click();
 await page.getByRole('button',{name:'Kinerja & Beban Kerja',exact:true}).click();await page.getByRole('searchbox',{name:'Cari nama PIC AT'}).fill('desta');await expect(page.locator('.workload-kpi tbody tr')).toHaveCount(1);await expect(page.locator('.workload-kpi tbody td').nth(2)).toHaveText('95');await page.locator('.workload-kpi tbody td').nth(2).getByRole('button').click();await expect(page.locator('.records .table-heading small')).toHaveText('95 data');expect(errors).toEqual([]);
});
test('import original workbook, source export and restore work without silently dropping rows',async({page})=>{
 await page.getByRole('button',{name:'Data',exact:true}).click();await expect(page.locator('.records tbody tr')).toHaveCount(10);await page.locator('.records').getByRole('button',{name:'Berikutnya',exact:true}).click();await expect(page.locator('.records tbody td').first()).toHaveText('11');
 await page.locator('input[type=file]').setInputFiles('C:/Users/36513/Downloads/DETAIL_DATA_AT_MATCH_DISCREPANCY_v2.xlsx');await expect(page.getByText('Validasi berhasil',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Pratinjau Impor: 257 Baris'})).toBeVisible();await page.getByRole('button',{name:'Terapkan Impor',exact:true}).click();await expect(page.locator('.records .table-heading small')).toHaveText('257 data');
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Unduh Excel',exact:true}).click();const download=await pending;expect(download.suggestedFilename()).toBe('corporate_piloting.xlsx');await page.getByRole('button',{name:'Pulihkan Data Awal',exact:true}).click();await expect(page.locator('.records .table-heading small')).toHaveText('257 data');
});
test('all and individual Word/PowerPoint exports, bilingual menus and responsive layout',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('private/pilot-reports',{recursive:true});
 for(const width of [1440,390])for(const language of ['id','en']){await page.setViewportSize({width,height:960});await page.getByLabel('Bahasa / Language').selectOption(language);for(const name of await page.locator('.tabs button').allTextContents()){await page.locator('.tabs').getByRole('button',{name,exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);}}
 await page.setViewportSize({width:1440,height:960});await page.getByLabel('Bahasa / Language').selectOption('id');await page.getByRole('button',{name:'Report',exact:true}).click();
 for(const person of ['', 'Desta','Irfan','Resti','Tari'])for(const format of ['pptx','docx']){await page.locator('.report-fields select').first().selectOption(person);await page.locator('.report-fields select').nth(1).selectOption(format);const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Buat Report',exact:true}).click();const file=await wait;await file.saveAs(`private/pilot-reports/${person||'All'}.${format}`);}
 await page.getByRole('button',{name:'Ringkasan',exact:true}).click();await page.screenshot({path:'private/piloting-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'private/piloting-mobile.png',fullPage:true});expect(errors).toEqual([]);
});
