import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Buka preview lokal'}).click();});
test('Piloting dependent filters, month, report isolation and anchored account',async({page})=>{
 await page.getByRole('button',{name:'Corporate - Piloting',exact:true}).click();
 const menus=await page.locator('.tabs button').allTextContents();await page.getByRole('button',{name:'Corporate - Non Piloting',exact:true}).click();expect(await page.locator('.tabs button').allTextContents()).toEqual(menus);await page.getByRole('button',{name:'Corporate - Piloting',exact:true}).click();
 await expect(page.getByLabel('Subproduk',{exact:true})).toBeDisabled();await page.getByLabel('Produk',{exact:true}).selectOption('Virtual Account / e-Collection');await page.getByLabel('Subproduk',{exact:true}).selectOption('VA Debit');await expect(page.locator('.pilot-cards strong').first()).toHaveText('42');
 await page.locator('.period-trigger').click();await page.getByRole('radio',{name:'Bulanan',exact:true}).check();await page.getByLabel('Bulan',{exact:true}).fill('2026-08');await page.getByRole('button',{name:'Terapkan',exact:true}).click();await expect(page.locator('.period-trigger')).toContainText('Agustus 2026');await expect(page.locator('.pilot-cards strong').first()).toHaveText('42');
 await page.getByRole('button',{name:'Report',exact:true}).click();await expect(page.locator('.pilot-report-actions')).toContainText('257');await page.getByRole('button',{name:'Sesuai Filter Dashboard',exact:true}).click();await expect(page.locator('.pilot-report-actions')).toContainText('42');await page.getByRole('button',{name:'Custom Report',exact:true}).click();await expect(page.locator('.pilot-report-actions')).toContainText('257');const checkbox=await page.locator('.report-contents input').first().boundingBox();expect(checkbox!.width).toBeLessThanOrEqual(20);
 await page.getByRole('button',{name:'Ringkasan',exact:true}).click();await expect(page.getByLabel('Subproduk',{exact:true})).toHaveValue('VA Debit');
 await page.evaluate(()=>scrollTo(0,0));const before=await page.evaluate(()=>scrollY);await page.getByRole('button',{name:'Akun pengguna',exact:true}).click();const account=await page.locator('.profile-button').boundingBox(),panel=await page.locator('.account-popover').boundingBox();expect(panel!.y).toBeGreaterThan(account!.y);expect(panel!.y-account!.y).toBeLessThan(120);expect(await page.evaluate(()=>scrollY)).toEqual(before);await page.keyboard.press('Escape');await expect(page.locator('.account-popover')).toHaveCount(0);
 await page.getByRole('button',{name:'Reset Filter',exact:true}).click();expect(await page.locator('.pilot-trend svg text').count()).toBeLessThan(12);await page.locator('.pilot-trend svg circle[role=button]').first().hover();await expect(page.locator('.pilot-trend-tooltip')).toBeVisible();await page.screenshot({path:'private/revisions-overview.png',fullPage:true});
});
test('all dashboards export both report formats and no longer show Report Preview',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const dashboard of ['IJR - BNIdirect','Regional - Non BNIDirect','Corporate - Non Piloting','Corporate - Piloting']){
  await page.getByRole('button',{name:dashboard,exact:true}).click();await page.getByRole('button',{name:'Report',exact:true}).click();await expect(page.getByRole('button',{name:'Preview Report',exact:true})).toHaveCount(0);
  for(const format of ['pptx','docx']){await page.getByLabel('Format Report',{exact:true}).selectOption(format);const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Buat Report',exact:true}).click();const file=await wait;expect(file.suggestedFilename()).toMatch(new RegExp('\\.'+format+'$'));await file.saveAs('private/access-reports/'+dashboard.split(' - ')[0]+'-'+(dashboard==='Corporate - Piloting'?'pilot':'standard')+'.'+format);}
 }
 expect(errors).toEqual([]);
});
