import { useMemo, useState } from 'react';
import { type MonitoringRecord, type Payload, type SlaRule } from '../types';
import { Panel, Bars, Donut } from '../components/Charts';
import { initialFilters, field, value, filterPiloting, breakdown, pilotMetrics, people, type PilotFilters } from './model';
import { PilotRecords, PilotDetail, PilotTable, usePilotText } from './ui';
import { readPiloting, exportPiloting } from './imports';
import { PilotFilterBar } from './PilotFilters';
import { PilotTrend } from './PilotTrend';
import { PilotSla } from './PilotSla';
import { PilotReport } from './PilotReport';
import { slaMetrics } from './sla';
import './piloting.css';
interface Props { rows:MonitoringRecord[];canEdit:boolean;onApply:(rows:Payload[],name:string)=>Promise<void>;onRestore:()=>Promise<void>;rules:SlaRule[];onSaveRule:(r:SlaRule)=>Promise<void>;onDeleteRule:(s:string)=>Promise<void> }
export default function PilotingDashboard({rows,canEdit,onApply,onRestore,rules,onSaveRule,onDeleteRule}:Props) {
 const t=usePilotText(),[view,setView]=useState('overview'),[filters,setFilters]=useState<PilotFilters>({...initialFilters}),[detail,setDetail]=useState<MonitoringRecord|null>(null),[drill,setDrill]=useState<{title:string;rows:MonitoringRecord[]}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[imported,setImported]=useState<Awaited<ReturnType<typeof readPiloting>>|null>(null),[fileName,setFileName]=useState('');
 const filtered=useMemo(()=>filterPiloting(rows,filters),[rows,filters]),m=pilotMetrics(filtered),personRows=useMemo(()=>people(filtered).map(p=>({...p,...slaMetrics(p.rows)})).filter(p=>p.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[filtered,query]);
 const update=(key:keyof PilotFilters,v:string)=>{setFilters(f=>({...f,[key]:v}));setDrill(null);};
 const toggle=(key:keyof PilotFilters,v:string)=>update(key,filters[key]===v?'':v);
 const tabs=[['overview','Ringkasan'],['process','Proses Implementasi'],['people','Kinerja & Beban Kerja'],['report','Report'],['data','Data']];
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const cards:[string,number,keyof PilotFilters|null,string][]=[['Total Permohonan',m.total,null,''],['Selesai',m.done,'status','Done'],['Reject/Retur',m.returned,'status','Reject/Retur'],['Pending',m.pending,'status','Masih Pending'],['Discrepancy',m.discrepancy,'discrepancy','Discrepancy']];
 const chart=(title:string,key:'group'|'product'|'form'|'status'|'discrepancy')=><Panel title={t(title)} hint={t('Klik untuk melihat permohonan')}><Bars items={breakdown(filtered,field[key])} color="#087f8c" onSelect={v=>toggle(key,v)}/></Panel>;
 return <div className="dashboard-content dash-piloting"><nav className="tabs" aria-label={t('Dashboard sections')}>{tabs.map(([id,label])=><button key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>{setView(id);setDrill(null);setError('');}}>{t(label)}</button>)}</nav>
 {view!=='report'&&<PilotFilterBar rows={rows} filters={filters} onChange={f=>{setFilters(f);setDrill(null);}}/>}
 {error&&<p className="error" role="alert">{error}</p>}
 {view==='overview'&&<><div className="kpis pilot-cards">{cards.map(([label,n,key,v],i)=><button key={label} className={'kpi source-'+['blue','green','red','amber','purple'][i]} disabled={!key} onClick={()=>key&&toggle(key,v)}><small>{t(label)}</small><strong>{n.toLocaleString()}</strong><span>{t(key==='discrepancy'?'Bagian dari total permohonan':'Data sesuai filter aktif')}</span></button>)}</div><p className="pilot-note">{t('Status dan discrepancy ditampilkan terpisah.')}</p></>}
 {view==='overview'&&<><div className="grid-three"><Panel title={t('Status Pekerjaan')}><Donut items={breakdown(filtered,field.status)} colorByName={{Done:'#087f8c','Reject/Retur':'#f97316','Masih Pending':'#173a63'}} onSelect={v=>toggle('status',v)}/></Panel>{chart('Produk Terbanyak','product')}{chart('Permohonan per Kelompok','group')}</div><div className="grid-two"><Panel title={t('Tren Assign ke AT')}><PilotTrend items={breakdown(filtered,field.assigned).sort((a,b)=>a[0].localeCompare(b[0]))}/></Panel>{chart('Jenis Pekerjaan','form')}</div></>}
 {view==='people'&&<PilotSla rows={filtered} rules={rules} canEdit={canEdit} onSave={onSaveRule} onDelete={onDeleteRule} onOpen={setDetail} onDrill={(title,rows)=>setDrill({title,rows})}/>}
 {view==='process'&&<div className="grid-two">{chart('Status Pekerjaan','status')}{chart('Jenis Pekerjaan','form')}<Panel title={t('Tren Assign ke AT')}><PilotTrend items={breakdown(filtered,field.assigned).sort((a,b)=>a[0].localeCompare(b[0]))}/></Panel></div>}
 {view==='people'&&<section className="panel workload-kpi pilot-kpi"><div className="panel-head"><h3>{t('Kinerja & Beban Kerja')}</h3></div><div className="pilot-toolbar"><input type="search" aria-label={t('Cari nama PIC AT')} placeholder={t('Cari nama PIC AT')} value={query} onChange={e=>setQuery(e.target.value)}/><span>{personRows.length} {t('hasil')}</span></div><PilotTable rows={personRows} idOf={p=>p.name} columns={[{label:'No.',render:(_,i)=>i+1},{label:'Nama',render:p=><button className="text-button" onClick={()=>setDrill({title:p.name,rows:p.rows})}>{p.name}</button>},...(['total','done','returned','pending','discrepancy'] as const).map((key,i)=>({label:['Total Permohonan','Selesai','Reject/Retur','Pending','Discrepancy'][i],render:(p:typeof personRows[number])=><button className="text-button pilot-table-number" onClick={()=>setDrill({title:p.name+' · '+t(['Total Permohonan','Selesai','Reject/Retur','Pending','Discrepancy'][i]),rows:key==='total'?p.rows:p.rows.filter(r=>key==='discrepancy'?value(r,field.discrepancy)==='Discrepancy':value(r,field.status)===({done:'Done',returned:'Reject/Retur',pending:'Masih Pending'} as const)[key])})}>{p[key].toLocaleString()}</button>})),...(['within','overdue'] as const).map(key=>({label:key==='within'?'Within SLA':'Overdue',render:(p:typeof personRows[number])=><button className="text-button" onClick={()=>setDrill({title:p.name+' · '+t(key==='within'?'Within SLA':'Overdue'),rows:p.rows.filter(r=>r.sla.status===(key==='within'?'Within SLA':'Overdue'))})}>{p[key]}</button>})),{label:'SLA Achievement',render:p=>p.achievement===null?'—':p.achievement.toFixed(1)+'%'},{label:'Rata-rata Hari Kerja',render:p=>p.average===null?'—':p.average.toFixed(1)}]}/><p className="pilot-note">{t('Pekerjaan selesai dengan durasi tersedia')}: {m.measurable.toLocaleString()}</p></section>}
 {view==='data'&&<><section className="panel"><div className="panel-head"><h3>{t('Data Corporate - Piloting')}</h3><p>{t('Upload dan riwayat data tersedia pada menu Admin.')}</p></div><div className="button-row"><button className="secondary" onClick={()=>exportPiloting(filtered.map(r=>r.payload),'xlsx')}>{t('Unduh Excel')}</button><button className="secondary" onClick={()=>exportPiloting(filtered.map(r=>r.payload),'csv')}>{t('Unduh CSV')}</button></div></section><PilotRecords rows={filtered} onOpen={setDetail}/></>}
 {view==='report'&&<PilotReport rows={rows} dashboardFilters={filters}/>}
 {drill&&<><div className="pilot-toolbar"><h3>{t(drill.title)}</h3><button className="secondary" onClick={()=>setDrill(null)}>{t('Tutup rincian')}</button></div><PilotRecords rows={drill.rows} onOpen={setDetail}/></>}{detail&&<PilotDetail row={detail} onClose={()=>setDetail(null)}/>}</div>;
}
