import { useMemo, useState } from 'react';
import { type MonitoringRecord, type Payload } from '../types';
import { Panel, Bars, Donut, Trend } from '../components/Charts';
import { initialFilters, field, value, filterPiloting, breakdown, pilotMetrics, people, duration, type PilotFilters } from './model';
import { PilotRecords, PilotDetail, PilotTable, usePilotText } from './ui';
import { readPiloting, exportPiloting } from './imports';
import { generatePilotReport, reportSections } from './reports';
import './piloting.css';
interface Props { rows:MonitoringRecord[];canEdit:boolean;onApply:(rows:Payload[],name:string)=>Promise<void>;onRestore:()=>Promise<void> }
export default function PilotingDashboard({rows,canEdit,onApply,onRestore}:Props) {
 const t=usePilotText(),[view,setView]=useState('overview'),[filters,setFilters]=useState<PilotFilters>({...initialFilters}),[detail,setDetail]=useState<MonitoringRecord|null>(null),[drill,setDrill]=useState<{title:string;rows:MonitoringRecord[]}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[imported,setImported]=useState<Awaited<ReturnType<typeof readPiloting>>|null>(null),[fileName,setFileName]=useState(''),[format,setFormat]=useState<'pptx'|'docx'>('pptx'),[reportPerson,setReportPerson]=useState(''),[selected,setSelected]=useState<string[]>(Object.keys(reportSections));
 const filtered=useMemo(()=>filterPiloting(rows,filters),[rows,filters]),m=pilotMetrics(filtered),personRows=useMemo(()=>people(filtered).filter(p=>p.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[filtered,query]);
 const update=(key:keyof PilotFilters,v:string)=>{setFilters(f=>({...f,[key]:v}));setDrill(null);};
 const toggle=(key:keyof PilotFilters,v:string)=>update(key,filters[key]===v?'':v);
 const tabs=[['overview','Ringkasan'],['process','Proses Implementasi'],['people','Kinerja & Beban Kerja'],['report','Report'],['data','Data']];
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const cards:[string,number,keyof PilotFilters|null,string][]=[['Total Permohonan',m.total,null,''],['Selesai',m.done,'status','Done'],['Reject/Retur',m.returned,'status','Reject/Retur'],['Pending',m.pending,'status','Masih Pending'],['Discrepancy',m.discrepancy,'discrepancy','Discrepancy']];
 const chart=(title:string,key:'group'|'product'|'form'|'status'|'discrepancy')=><Panel title={t(title)} hint={t('Klik untuk melihat permohonan')}><Bars items={breakdown(filtered,field[key])} color="#087f8c" onSelect={v=>toggle(key,v)}/></Panel>;
 return <div className="dashboard-content dash-piloting"><nav className="tabs" aria-label={t('Dashboard sections')}>{tabs.map(([id,label])=><button key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>{setView(id);setDrill(null);setError('');}}>{t(label)}</button>)}</nav>
 <section className="filter-panel pilot-filters"><label>{t('Pencarian')}<input aria-label={t('Cari data')} placeholder={t('Cari nomor register, perusahaan, PIC…')} value={filters.search} onChange={e=>update('search',e.target.value)}/></label><label>{t('Periode Assign ke AT')}<input type="date" aria-label={t('Start Date')} value={filters.from} onChange={e=>update('from',e.target.value)}/></label><label>{t('End Date')}<input type="date" min={filters.from||undefined} value={filters.to} onChange={e=>update('to',e.target.value)}/></label>{(['group','person','product','form','status','discrepancy'] as const).map(key=><label key={key}>{t(({group:'Kelompok',person:'PIC AT',product:'Produk',form:'Jenis Formulir',status:'Status Pekerjaan',discrepancy:'Status Discrepancy'})[key])}<select aria-label={t(({group:'Kelompok',person:'PIC AT',product:'Produk',form:'Jenis Formulir',status:'Status Pekerjaan',discrepancy:'Status Discrepancy'})[key])} value={filters[key]} onChange={e=>update(key,e.target.value)}><option value="">{t('Semua')}</option>{breakdown(rows,field[key]).map(([name])=><option key={name} value={name}>{name}</option>)}</select></label>)}<button className="secondary" onClick={()=>{setFilters({...initialFilters});setDrill(null);}}>{t('Reset Filter')}</button></section>
 {error&&<p className="error" role="alert">{error}</p>}
 {['overview','process'].includes(view)&&<><div className="kpis pilot-cards">{cards.map(([label,n,key,v],i)=><button key={label} className={'kpi source-'+['blue','green','red','amber','purple'][i]} disabled={!key} onClick={()=>key&&toggle(key,v)}><small>{t(label)}</small><strong>{n.toLocaleString()}</strong><span>{t(key==='discrepancy'?'Bagian dari total permohonan':'Data sesuai filter aktif')}</span></button>)}</div><p className="pilot-note">{t('Status dan discrepancy ditampilkan terpisah.')}</p></>}
 {view==='overview'&&<><div className="grid-three"><Panel title={t('Status Pekerjaan')}><Donut items={breakdown(filtered,field.status)} colorByName={{Done:'#087f8c','Reject/Retur':'#f97316','Masih Pending':'#173a63'}} onSelect={v=>toggle('status',v)}/></Panel>{chart('Produk Terbanyak','product')}{chart('Permohonan per Kelompok','group')}</div><div className="grid-two"><Panel title={t('Tren Assign ke AT')}><Trend items={breakdown(filtered,field.assigned).sort((a,b)=>a[0].localeCompare(b[0]))}/></Panel>{chart('Jenis Pekerjaan','form')}</div></>}
 {view==='process'&&<><section className="duration-card"><div className="panel-head"><h3>{t('Durasi Pekerjaan Selesai')}</h3><p>{t('Jumlah permohonan berdasarkan hari kerja')}</p></div><div className="duration-grid">{['Same Day','1 Hari','2 Hari','>2 Hari','Unavailable'].map(bucket=>{const eligible=filtered.filter(r=>value(r,field.status)==='Done'&&duration(r)===bucket);return <button key={bucket} className={drill?.title===bucket?'active':''} onClick={()=>setDrill(drill?.title===bucket?null:{title:bucket,rows:eligible})}><strong>{eligible.length.toLocaleString()}</strong><span>{t(bucket==='Unavailable'?'Durasi belum tersedia':bucket)}</span></button>;})}</div></section><div className="grid-two">{chart('Distribusi Status AT','status')}{chart('Status Discrepancy','discrepancy')}</div><PilotRecords rows={filtered.filter(r=>value(r,field.discrepancy)==='Discrepancy')} onOpen={setDetail} title="Rincian Discrepancy"/></>}
 {view==='people'&&<section className="panel workload-kpi pilot-kpi"><div className="panel-head"><h3>{t('Kinerja & Beban Kerja')}</h3></div><div className="pilot-toolbar"><input type="search" aria-label={t('Cari nama PIC AT')} placeholder={t('Cari nama PIC AT')} value={query} onChange={e=>setQuery(e.target.value)}/><span>{personRows.length} {t('hasil')}</span></div><PilotTable rows={personRows} idOf={p=>p.name} columns={[{label:'No.',render:(_,i)=>i+1},{label:'Nama',render:p=><button className="text-button" onClick={()=>setDrill({title:p.name,rows:p.rows})}>{p.name}</button>},...(['total','done','returned','pending','discrepancy'] as const).map((key,i)=>({label:['Total Permohonan','Selesai','Reject/Retur','Pending','Discrepancy'][i],render:(p:typeof personRows[number])=><button className="text-button pilot-table-number" onClick={()=>setDrill({title:p.name+' · '+t(['Total Permohonan','Selesai','Reject/Retur','Pending','Discrepancy'][i]),rows:key==='total'?p.rows:p.rows.filter(r=>key==='discrepancy'?value(r,field.discrepancy)==='Discrepancy':value(r,field.status)===({done:'Done',returned:'Reject/Retur',pending:'Masih Pending'} as const)[key])})}>{p[key].toLocaleString()}</button>})),{label:'Rata-rata Hari Kerja',render:p=>p.average===null?'—':p.average.toFixed(1)}]}/><p className="pilot-note">{t('Pekerjaan selesai dengan durasi tersedia')}: {m.measurable.toLocaleString()}</p></section>}
 {view==='data'&&<><section className="panel"><div className="panel-head"><h3>{t('Impor Data Piloting')}</h3><p>{t('Impor mengganti data aktif setelah validasi; data awal tetap tersedia untuk dipulihkan.')}</p></div><div className="button-row"><button className="secondary" onClick={()=>exportPiloting(filtered.map(r=>r.payload),'xlsx')}>{t('Unduh Excel')}</button><button className="secondary" onClick={()=>exportPiloting(filtered.map(r=>r.payload),'csv')}>{t('Unduh CSV')}</button>{canEdit&&<button className="secondary" disabled={busy} onClick={()=>perform(onRestore)}>{t('Pulihkan Data Awal')}</button>}</div>{canEdit&&<><label>{t('Pilih file Excel')}<input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];setImported(null);if(file)perform(async()=>{setFileName(file.name);setImported(await readPiloting(file));});}}/></label>{imported&&<div><h4>{t('Pratinjau Impor')}: {imported.rows.length} {t('Baris')}</h4>{imported.errors.length?<ul className="error">{imported.errors.slice(0,10).map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>{t('Validasi berhasil')}</p>}<button className="primary" disabled={busy||!!imported.errors.length||!imported.rows.length} onClick={()=>perform(async()=>{await onApply(imported.rows,fileName);setImported(null);})}>{t(busy?'Menyimpan…':'Terapkan Impor')}</button></div>}</>}</section><PilotRecords rows={filtered} onOpen={setDetail}/></>}
 {view==='report'&&<section className="panel"><div className="panel-head"><h3>{t('Laporan Monitoring')}</h3></div><div className="report-fields"><label>{t('PIC AT')}<select value={reportPerson} onChange={e=>setReportPerson(e.target.value)}><option value="">{t('Seluruh PIC AT')}</option>{breakdown(rows,field.person).map(([name])=><option key={name}>{name}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value as 'pptx'|'docx')}><option value="pptx">PowerPoint (.pptx)</option><option value="docx">Word (.docx)</option></select></label></div><h4>{t('Bagian Report')}</h4><div className="pilot-sections">{Object.entries(reportSections).map(([key,label])=><label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={()=>setSelected(a=>a.includes(key)?a.filter(x=>x!==key):[...a,key])}/>{t(label)}</label>)}</div><p className="pilot-note">{(reportPerson?filtered.filter(r=>value(r,field.person)===reportPerson):filtered).length} {t('Data sesuai filter aktif')}</p><button className="primary" disabled={busy||!selected.length||!(reportPerson?filtered.filter(r=>value(r,field.person)===reportPerson):filtered).length} onClick={()=>perform(()=>generatePilotReport(filtered,reportPerson,format,selected,filters))}>{t(busy?'Memproses…':'Buat Report')}</button></section>}
 {drill&&<><div className="pilot-toolbar"><h3>{t(drill.title)}</h3><button className="secondary" onClick={()=>setDrill(null)}>{t('Tutup rincian')}</button></div><PilotRecords rows={drill.rows} onOpen={setDetail}/></>}{detail&&<PilotDetail row={detail} onClose={()=>setDetail(null)}/>}</div>;
}
