import { useEffect, useRef, useState, type ReactNode } from 'react';
import { pendingAge } from './sla';
import { X } from 'lucide-react';
import { useLanguage } from '../lib/language';
import { type MonitoringRecord, text } from '../types';
import { sourceFields, field, value } from './model';
import { exportPiloting } from './imports';
const english: Record<string,string> = {
  'Total Permohonan':'Total Requests','Selesai':'Completed','Pending':'Pending','Reject/Retur':'Rejected / Returned','Discrepancy':'Discrepancy','Bagian dari total permohonan':'Subset of total requests','Periode Assign ke AT':'Assigned to AT Period','Kelompok':'Group','Segmen':'Segment','Permohonan per Segmen':'Requests by Segment','PIC AT':'AT Person','Jenis Formulir':'Form Type','Status Pekerjaan':'Work Status','Status Discrepancy':'Discrepancy Status','Semua':'All','Pencarian':'Search','Cari nomor register, perusahaan, PIC…':'Search register number, company, person…','Permohonan per Kelompok':'Requests by Group','Tren Assign ke AT':'Requests Assigned to AT','Produk Terbanyak':'Top Products','Jenis Pekerjaan':'Work Type','Durasi Pekerjaan Selesai':'Completed Work Duration','Jumlah permohonan berdasarkan hari kerja':'Number of requests by business days','Durasi belum tersedia':'Duration unavailable','Distribusi Status AT':'AT Status Distribution','Rincian Discrepancy':'Discrepancy Details','Cari nama PIC AT':'Search AT person','Rata-rata Hari Kerja':'Average Business Days','Hari Kerja':'Business Days','Tutup rincian':'Close details','Tutup detail':'Close detail','Detail Permohonan':'Request Details','Tanggal Assign':'Assigned Date','Tanggal Selesai':'Completed Date','Nomor Register':'Register Number','Perusahaan':'Company','Produk':'Product','Nama':'Name','Berikutnya':'Next','Sebelumnya':'Previous','Halaman':'Page','Tidak ada data.':'No data.','Impor Data Piloting':'Import Piloting Data','Pilih file Excel':'Choose Excel file','Pratinjau Impor':'Import Preview','Terapkan Impor':'Apply Import','Pulihkan Data Awal':'Restore Original Data','Unduh Excel':'Download Excel','Unduh CSV':'Download CSV','Seluruh PIC AT':'All AT People','Buat Report':'Generate Report','Bagian Report':'Report Sections','Laporan Monitoring':'Monitoring Report','Waktu Penyelesaian':'Completion Time','Pemenuhan sesuai sumber':'Fulfillment as recorded','Data sesuai filter aktif':'Data matching active filters','Status dan discrepancy ditampilkan terpisah.':'Work status and discrepancy are shown separately.','Pekerjaan selesai dengan durasi tersedia':'Completed requests with available duration','Reset Filter':'Reset Filters','Klik untuk melihat permohonan':'Click to view requests','Menyimpan…':'Saving…','Memproses…':'Processing…','Batalkan':'Cancel','Baris':'Rows','data':'records','hasil':'results','Validasi berhasil':'Validation passed','Impor mengganti data aktif setelah validasi; data awal tetap tersedia untuk dipulihkan.':'Import replaces active data after validation; original data remains available to restore.'
};
export function usePilotText() { const {language,t} = useLanguage(); return (s:string) => { const label=s==='Masih Pending'?'Pending':s.replace(/Kelompok/g,'Segmen'); return language==='en' ? english[label]||t(label) : t(label); }; }
export function Pager({page,pages,onChange}:{page:number;pages:number;onChange:(n:number)=>void}) {const t=usePilotText();return <div className="pagination"><button className="secondary" disabled={page<=1} onClick={()=>onChange(page-1)}>{t('Sebelumnya')}</button><span>{t('Halaman')} {page} / {pages}</span><button className="secondary" disabled={page>=pages} onClick={()=>onChange(page+1)}>{t('Berikutnya')}</button></div>;}
export type Column<T> = {label:string;render:(row:T,index:number)=>ReactNode};
export function PilotTable<T>({rows,columns,idOf}:{rows:T[];columns:Column<T>[];idOf:(row:T)=>string}) { const t=usePilotText(),[page,setPage]=useState(1);useEffect(()=>setPage(1),[rows]);const pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages),start=(current-1)*10;return <><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.label}>{t(c.label)}</th>)}</tr></thead><tbody>{rows.slice(start,start+10).map((r,i)=><tr key={idOf(r)}>{columns.map(c=><td key={c.label}>{c.render(r,start+i)}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}>{t('Tidak ada data.')}</td></tr>}</tbody></table></div><Pager page={current} pages={pages} onChange={setPage}/></>; }
export function PilotRecords({rows,onOpen,title='Detail Permohonan'}:{rows:MonitoringRecord[];onOpen:(r:MonitoringRecord)=>void;title?:string}) {const t=usePilotText();return <section className="panel records"><div className="table-heading"><div><h3>{t(title)}</h3><small>{rows.length.toLocaleString()} {t('data')}</small></div><button className="secondary" onClick={()=>exportPiloting(rows.map(r=>r.payload),'csv')}>{t('Unduh CSV')}</button></div><PilotTable rows={rows} idOf={r=>r.id} columns={[{label:'No.',render:(_,i)=>i+1},{label:'Nomor Register',render:r=><button className="text-button" onClick={()=>onOpen(r)}>{value(r,field.id)}</button>},...[[field.company,'Perusahaan'],[field.group,'Kelompok'],[field.person,'PIC AT'],[field.product,'Produk'],[field.status,'Status Pekerjaan'],[field.assigned,'Tanggal Assign'],[field.completed,'Tanggal Selesai'],[field.days,'Hari Kerja'],[field.discrepancy,'Status Discrepancy']].map(([key,label])=>({label,render:(r:MonitoringRecord)=>key===field.status?t(value(r,key)||'—'):value(r,key)||'—'})),{label:'SLA Target',render:r=>r.sla.target??'—'},{label:'SLA Status',render:r=>value(r,field.status)==='Done'?t(r.sla.status):'—'},{label:'Umur Pending (hari kerja)',render:r=>pendingAge(r)??'—'}]}/></section>;}
export function PilotDetail({row,onClose}:{row:MonitoringRecord;onClose:()=>void}){const t=usePilotText(),ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="detail-dialog" ref={ref} onClose={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="dialog-head"><div><h2>{value(row,field.company)}</h2><p>{value(row,field.id)}</p></div><button className="icon-button" aria-label={t('Tutup detail')} onClick={onClose}><X/></button></div><div className="detail-grid">{[...sourceFields].map(key=><div key={key}><small>{t(key)}</small><p>{key===field.status?t(text(row.payload[key])||'—'):text(row.payload[key])||'—'}</p></div>)}{[['SLA Target',row.sla.target],['SLA Real',row.sla.real],['SLA Status',value(row,field.status)==='Done'?t(row.sla.status):'—'],['SLA Solution',row.sla.solution],['SLA Over By',row.sla.over],['Umur Pending (hari kerja)',pendingAge(row)]].map(([name,v])=><div key={String(name)}><small>{t(String(name))}</small><p>{v??'—'}</p></div>)}</div></dialog>;}
