import {useTheme,themes,themeNames,type Theme} from '../lib/theme';
import { useEffect, useRef } from 'react';
import { ChevronDown } from 'lucide-react';
import { useLanguage } from '../lib/language';
export function AccountMenu({onPassword,name,email,role,preview,open,onToggle,onClose,displayName,onNameChange,onSave}:{onPassword:()=>void;name:string;email:string;role:string;preview:boolean;open:boolean;onToggle:()=>void;onClose:()=>void;displayName:string;onNameChange:(s:string)=>void;onSave:()=>Promise<void>}) {
  const {theme,setTheme}=useTheme();
  const {t,language,setLanguage}=useLanguage(),ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!open)return;const outside=(e:MouseEvent)=>{if(e.target instanceof Node&&!ref.current?.contains(e.target))onClose();},escape=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('mousedown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',escape);};},[open,onClose]);
  return <div className="account-area" ref={ref}><button className="profile-button" aria-label={t('Akun pengguna')} aria-expanded={open} onClick={onToggle}><span>{name.slice(0,2).toUpperCase()}</span><div><b title={name}>{name}</b><small>{preview?t('Preview lokal'):role} · {language==='en'?'English':'Indonesia'} <ChevronDown size={12}/></small></div></button>{open&&<section className="account-popover" role="dialog" aria-label={t('Profile')}><div className="account-popover-heading"><span className="account-avatar">{name.slice(0,2).toUpperCase()}</span><div><b>{name}</b><small>{role}</small></div></div><label>{t('Nama tampilan')}<input value={displayName} onChange={e=>onNameChange(e.target.value)} placeholder={name}/></label><label>{t('Bahasa')}<select aria-label="Bahasa / Language" value={language} onChange={e=>setLanguage(e.target.value==='en'?'en':'id')}><option value="id">Indonesia</option><option value="en">English</option></select></label><label>{t('Warna Tema')}<select aria-label="Warna Tema" value={theme} onChange={e=>setTheme(e.target.value as Theme)}>{themes.map(value=><option key={value} value={value}>{themeNames[value]}</option>)}</select></label><div className="button-row">{!preview&&<button className="primary" onClick={onSave}>{t('Simpan')}</button>}<button className="secondary" onClick={onClose}>{t('Tutup')}</button></div>{!preview&&<button className="text-button" onClick={onPassword}>{t('Ganti Password')}</button>}<span className="sr-only">{email}</span></section>}</div>;
}
