import {DrillSlot} from './InlineDrill';
import { type MonitoringRecord, text } from '../types';
import { counts, status } from '../domain/analytics';
import { field, value, duration } from '../piloting/model';
import { Panel, Bars, Donut, Trend } from './Charts';
import { useLanguage } from '../lib/language';
import { PilotTrend } from '../piloting/PilotTrend';
type Props={rows:MonitoringRecord[];piloting?:boolean;onSelect:(key:'status'|'product'|'region',value:string)=>void;onDrill:(title:string,rows:MonitoringRecord[])=>void};
export function CorporateOverview({rows,piloting=false,onSelect,onDrill}:Props){
 const {t}=useLanguage(),measured=rows.filter(r=>['Within SLA','Overdue'].includes(r.sla.status));
 const get=(key:'status'|'product'|'region'|'date',r:MonitoringRecord)=>piloting?value(r,field[key==='region'?'group':key==='date'?'assigned':key]):key==='status'?status(r,'corporate'):text(r.payload[key==='region'?'segment':key==='date'?'createDate':'product']);
 return <><div className="grid-three"><Panel title={t('SLA Performance')} hint={t('Data terukur')}><Donut items={counts(measured,r=>r.sla.status)} colorByName={{'Within SLA':'#159B70',Overdue:'#D55666'}} onSelect={v=>onDrill(v,measured.filter(r=>r.sla.status===v))}/></Panel><Panel title={t('Volume by Segment')}><Bars items={counts(rows,r=>get('region',r))} onSelect={v=>{onSelect('region',v);onDrill(t('Volume by Segment')+' / '+v,rows.filter(r=>get('region',r)===v));}}/></Panel><Panel title={t('Top Products')}><Bars items={counts(rows,r=>get('product',r))} onSelect={v=>{onSelect('product',v);onDrill(t('Top Products')+' / '+v,rows.filter(r=>get('product',r)===v));}}/></Panel></div><Panel title={t(piloting?'Tren Assign ke AT':'Request Trend')}><PilotTrend items={counts(rows,r=>get('date',r)).filter(([date])=>/^\d{4}-\d{2}-\d{2}$/.test(date)).sort((a,b)=>a[0].localeCompare(b[0]))}/></Panel></>;
}
export function CorporateProcess({rows,piloting=false,onDrill}:Props){
 const {t}=useLanguage(),rawStatus=(r:MonitoringRecord)=>piloting?value(r,field.status):text(r.payload.status);
 const pending=(r:MonitoringRecord)=>piloting?value(r,field.status)==='Masih Pending':status(r,'corporate')==='Pending Task';
 const get=(key:'product'|'segment'|'type',r:MonitoringRecord)=>(piloting?value(r,field[key==='segment'?'group':key==='type'?'form':'product']):text(r.payload[key==='type'?'projectType':key]))||'\u2014';
 const buckets=['Same Day','1 Hari','2 Hari','>2 Hari','Unavailable'];
 const bucket=(r:MonitoringRecord)=>{if(piloting)return duration(r);const n=r.sla.real;return n===null||!Number.isFinite(n)?'Unavailable':n===0?'Same Day':n===1?'1 Hari':n===2?'2 Hari':'>2 Hari';};
 const durations=piloting?rows.filter(r=>value(r,field.status)==='Done'):rows;
 const breakdown=(title:string,key:'product'|'segment'|'type')=><Panel title={t(title)} hint={t('Klik bar untuk melihat nama PIC dan pekerjaan.')}><Bars limit={25} items={counts(rows,r=>get(key,r))} onSelect={name=>onDrill(t(title)+' / '+name,rows.filter(r=>get(key,r)===name))}/></Panel>;
 return <div className="corporate-process"><div data-drill-anchor="process-summary" className="person-kpis process-summary"><button onClick={()=>onDrill(t('Total Data'),rows)}><small>{t('Total Data')}</small><b>{rows.length.toLocaleString()}</b></button>{counts(rows,r=>piloting?rawStatus(r):status(r,'corporate')).map(([name,n])=><button key={name} onClick={()=>onDrill(name==='Masih Pending'?t('Pending'):name,rows.filter(r=>(piloting?rawStatus(r):status(r,'corporate'))===name))}><small>{name==='Masih Pending'?t('Pending'):t(name)}</small><b>{n.toLocaleString()}</b></button>)}</div><DrillSlot anchor="process-summary"/><Panel title={t('Durasi Implementasi')} hint={t(piloting?'Pekerjaan selesai berdasarkan hari penyelesaian AT.':'Hari kerja dari tanggal Assign sampai tanggal Done.')}><div className="duration-grid">{buckets.map(b=>{const scoped=durations.filter(r=>bucket(r)===b);return <button key={b} onClick={()=>onDrill(t(b==='Unavailable'?'Durasi belum tersedia':b),scoped)}><strong>{scoped.length.toLocaleString()}</strong><span>{t(b==='Unavailable'?'Durasi belum tersedia':b)}</span></button>;})}</div></Panel><div className="grid-two">{breakdown('Volume by Segment','segment')}{breakdown('Jenis Pekerjaan','type')}{breakdown('Top Products','product')}<Panel title={t('Pekerjaan Pending')} hint={t('Klik bar untuk melihat nama PIC dan pekerjaan.')}><Bars items={counts(rows.filter(pending),r=>(piloting?value(r,field.person):text(r.payload.implementor))||'\u2014')} onSelect={name=>onDrill(t('Pending')+' / '+name,rows.filter(r=>((piloting?value(r,field.person):text(r.payload.implementor))||'\u2014')===name&&pending(r)))}/></Panel></div></div>;
}
