import { RotateCcw } from 'lucide-react';
import { type DatasetKind, type MonitoringRecord, type Filters, type FilterKey, text, emptyFilters } from '../types';
import { fields, options, people, status, productCategory } from '../domain/analytics';
import { PeriodPicker } from './PeriodPicker';
export function FilterBar({ rows, kind, value, onChange }: {
    rows: MonitoringRecord[];
    kind: DatasetKind;
    value: Filters;
    onChange: (f: Filters) => void;
}) {
    const k = fields[kind], set = (key: FilterKey, v: string) => onChange({ ...value, [key]: v });
    const select = (key: FilterKey, label: string, values: string[]) => <label key={key}>{label}<select aria-label={label} value={value[key]} onChange={e => set(key, e.target.value)}><option value="">Semua {label}</option>{values.map(v => <option key={v}>{v}</option>)}</select></label>;
    const uniq = (values: string[]) => [...new Set(values.filter(Boolean))].sort();
    return <section className="filter-panel"><div className={'primary-filters filter-' + kind}><label>Search<input aria-label="Cari data" placeholder={kind === 'ijr' ? 'Application no, applicant, PIC...' : 'Company, CID, produk, implementor...'} value={value.search} onChange={e => set('search', e.target.value)}/></label><PeriodPicker value={value} onChange={onChange}/>{kind === 'ijr' ? <>{select('type', 'Application Type', options(rows, k.type))}{select('status', 'Status', uniq(rows.map(r => status(r, kind))))}{select('flow', 'Flow Process', options(rows, 'Flow Process'))}{select('region', 'Wilayah', options(rows, k.region))}</> : kind === 'regional' ? <>{select('region', 'Wilayah', options(rows, k.region))}{select('status', 'Status', uniq(rows.map(r => status(r, kind))))}{select('type', 'New / Maintenance', options(rows, k.type))}{select('category', 'TB Produk', uniq(rows.map(r => productCategory(text(r.payload.product), kind))))}{select('product', 'Sub TB Produk', options(rows, 'product'))}{select('person', 'Implementor (HO)', uniq(rows.flatMap(r => people(r, kind))))}</> : <>{select('region', 'Segment', options(rows, k.region))}{select('type', 'Project Type', options(rows, k.type))}{select('category', 'Product', uniq(rows.map(r => productCategory(text(r.payload.product), kind))))}{select('product', 'Sub Product', options(rows, 'product'))}{select('status', 'Status', uniq(rows.map(r => status(r, kind))))}{select('sla', 'SLA Status', ['Within SLA', 'Overdue', 'Without SLA', 'SLA Real Unavailable'])}</>}<button className="secondary" onClick={() => onChange({ ...emptyFilters })}><RotateCcw size={14}/>Reset</button></div><details className="advanced-filters"><summary>Filter tambahan</summary><div className="filters">{select('period', 'Periode', uniq(rows.map(r => text(r.payload[k.date]).slice(0, 7))))}{kind === 'ijr' && <>{select('branch', 'Cabang', options(rows, 'Cabang'))}{select('person', 'PIC / Implementor', uniq(rows.flatMap(r => people(r, kind, true))))}</>}{kind !== 'corporate' && select('sla', 'SLA', ['Within SLA', 'Overdue', 'Without SLA', 'SLA Real Unavailable'])}</div></details>{Object.entries(value).some(([, v]) => v) && <div className="chips">{Object.entries(value).filter(([, v]) => v).map(([key, v]) => <button key={key} onClick={() => set(key as FilterKey, '')}>{v}<span>×</span></button>)}</div>}</section>;
}
