import { useState } from 'react';
import { type MonitoringRecord, text } from '../types';
import { useLanguage } from '../lib/language';
import { Badge } from './Records';
import { TaskDoneDialog } from './TaskDoneDialog';

export function MyTasks({rows,onOpen,onDone,canDone}:{rows:MonitoringRecord[];onOpen:(r:MonitoringRecord)=>void;onDone:(r:MonitoringRecord,note:string)=>Promise<void>;canDone:boolean}) {
 const {t}=useLanguage(),[selected,setSelected]=useState<MonitoringRecord|null>(null),[message,setMessage]=useState(''),[page,setPage]=useState(1),[mode,setMode]=useState('all');
 const done=(r:MonitoringRecord)=>text(r.payload.status).toLowerCase()==='done';
 const shown=rows.filter(r=>mode==='done'?done(r):mode==='active'?!done(r):true),pages=Math.max(1,Math.ceil(shown.length/10)),current=Math.min(page,pages);
 return <section className="panel my-tasks"><div className="panel-head"><h3>My Task</h3><p>{t('Pekerjaan yang menjadi tanggung jawab Anda.')}</p></div><div className="person-kpis">{[['Pekerjaan Saya',rows.length,'all'],['Selesai',rows.filter(done).length,'done'],['Aktif',rows.filter(r=>!done(r)).length,'active']].map(([label,n,key])=><button key={key} className={mode===key?'active':''} onClick={()=>{setMode(String(key));setPage(1);}}><small>{t(String(label))}</small><b>{n}</b></button>)}</div>{message&&<p role="status" className="success">{message}</p>}<div className="table-scroll"><table><thead><tr>{['Perusahaan','CID','Produk','Status','Email Sales','Dokumen Lengkap','Selesai Setting','Tanggal Done','Aksi'].map(h=><th key={h}>{t(h)}</th>)}</tr></thead><tbody>{shown.slice((current-1)*10,current*10).map(r=><tr key={r.id}><td><button className="text-button" onClick={()=>onOpen(r)}>{text(r.payload.company)}</button></td><td>{text(r.payload.cid)}</td><td>{text(r.payload.product)}</td><td><Badge value={text(r.payload.status)}/></td>{['salesDate','docComplete','settingDone','doneDate'].map(key=><td key={key}>{text(r.payload[key])||'\u2014'}</td>)}<td>{!done(r)&&<button className="primary" disabled={!canDone} onClick={()=>{setSelected(r);}}>{t('Tandai Done')}</button>}</td></tr>)}</tbody></table></div>{!shown.length&&<p className="empty">{t('Tidak ada pekerjaan sesuai filter.')}</p>}<div className="pagination"><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>{t('Sebelumnya')}</button><span>{current} / {pages} · {shown.length} {t('data')}</span><button className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>{t('Berikutnya')}</button></div>{selected&&<TaskDoneDialog row={selected} onClose={()=>setSelected(null)} onSave={async note=>{await onDone(selected,note);setMessage(t('Status Done tersimpan.'));}}/>}</section>;
}
