import { type ApplicationKind, datasetTitles } from '../types';
import { type Grant, type Profile, type Team } from '../lib/access';
import { useLanguage } from '../lib/language';
const choices=(Object.keys(datasetTitles) as ApplicationKind[]).flatMap(dataset=>(dataset==='piloting'?['AT','PM']:['AT']).map(source=>({dataset,source:source as 'AT'|'PM'})));
export function UserAccessEditor({profile,grants,onChange,teams,pics}:{profile:Profile;grants:Grant[];onChange:(g:Grant[])=>void;teams:Team[];pics:Record<string,string[]>}) {
 const {t}=useLanguage();
 if(['admin','super_admin'].includes(profile.role))return <p className="muted">{t(profile.role==='super_admin'?'Akses seluruh dashboard dan pengelolaan aplikasi.':'Akses upload data, pengguna, dan pemetaan tim.')}</p>;
 const update=(index:number,g:Grant)=>onChange(grants.map((old,i)=>i===index?g:old));
 return <div className="access-editor"><h4>{t('Dashboard & Pemetaan')}</h4>{Object.keys(datasetTitles).map(k=><datalist id={'pic-'+k} key={k}>{(pics[k]||[]).map(n=><option key={n} value={n}/>)}</datalist>)}{grants.map((g,index)=><div className="access-row" key={index}><label>{t('Dashboard')}<select aria-label={t('Dashboard akses')} value={g.dataset+':'+g.source} onChange={e=>{const [dataset,source]=e.target.value.split(':');update(index,{dataset:dataset as ApplicationKind,source:source as 'AT'|'PM',pic:'',team_id:null});}}>{choices.filter(c=>c.dataset===g.dataset&&c.source===g.source||!grants.some(x=>x.dataset===c.dataset&&x.source===c.source)).map(c=><option key={c.dataset+c.source} value={c.dataset+':'+c.source}>{datasetTitles[c.dataset]}{c.dataset==='piloting'?' · '+c.source:''}</option>)}</select></label>{profile.role==='individual'&&<label>{t('PIC dari data sumber')}<input aria-label={t('PIC dari data sumber')} list={'pic-'+g.dataset} value={g.pic} placeholder={t('Pilih nama PIC')} onChange={e=>update(index,{...g,pic:e.target.value})}/></label>}{['team_leader','individual'].includes(profile.role)&&<label>{t(profile.role==='individual'?'Tim (opsional)':'Tim')}<select aria-label={t('Tim akses')} value={g.team_id||''} onChange={e=>update(index,{...g,team_id:e.target.value||null})}><option value="">{t('Pilih tim')}</option>{teams.filter(x=>x.dataset===g.dataset&&x.source===g.source&&(profile.role==='individual'||!x.leader_id||x.leader_id===profile.user_id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<button className="secondary access-remove" onClick={()=>onChange(grants.filter((_,i)=>i!==index))}>{t('Hapus akses')}</button></div>)}<button className="secondary" disabled={grants.length>=choices.length} onClick={()=>{const c=choices.find(c=>!grants.some(g=>g.dataset===c.dataset&&g.source===c.source));if(c)onChange([...grants,{...c,pic:'',team_id:null}]);}}>{t('Tambah akses dashboard')}</button>{!grants.length&&<p className="muted">{t('Pilih dashboard dan pemetaan untuk mengaktifkan akses pengguna.')}</p>}</div>;
}
